# Tensors Basics
Libraries used to run this notebook

    1. Tensorflow==2.5 
    2. Python==3.6


## Introduction
This notebook includes some basic functionality of tensors which really helps a data-scientist/machine-learning engineer to build a model. Special thing about this notebook is, it is made for begineers. Most of my fresh grad friends want to be a data-scientist/machine learning engineer, as I am also in learning phase so I decided to write down things, notes or things which helps me and my juniors to climb ladder of success. So lets gets started


## Setup 

Follow setup.md file to setup your environment

[Setup Readme](./setup.md)


In [2]:

# Getting tensorflow version
import tensorflow as tf
print(tf.__version__)

2.2.0


# Some basic Confusions



### 1. What are tensors?
Tensors are just numerical representation of the information. 

e.g 
1. [[1,2,4,5],[2,3,4,5]]
2. [[1,2,3,4,5]]
3. [[2]]


### 2. Difference between tensors and arrays
An array is a grid of values that contains raw data and we use it to locate and interpret elements in the raw data. Whereas a tensor is a multidimensional array. Generally, we use NumPy for working with an array and TensorFlow for working with a tensor

## Scalars and Vectors
A scalar is an element of a field which is used to define a vector space. A quantity described by multiple scalars, such as having both direction and magnitude, is called a vector.[1]

In [16]:
# Constant
    # Create a constant tensor like object 
scalar = tf.constant(3)
print(scalar)

vector = tf.constant([3,2,3])
print(vector)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 2 3], shape=(3,), dtype=int32)


## Matrix
In mathematics, a matrix (plural matrices) is a rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns.[1][2] For example, the dimension of the matrix below is 2 × 3 (read "two by three"), because there are two rows and three columns:

1. Matrix 1

\begin{bmatrix}1&9&-13\\20&5&-6\end{bmatrix}

2. Matrix 2

\begin{bmatrix}1&9&-13\\20&5&-6\end{bmatrix}



In [14]:
matrix = tf.constant([[3, 2],
                     [1, 3],
                     [2, 4]])
print(matrix)

tf.Tensor(
[[3 2]
 [1 3]
 [2 4]], shape=(3, 2), dtype=int32)


# Ways to define tensor-object

There is another way to define tensorflow objects which is **tf.vatiable**, So, lets see what is the **difference** between tf.variable and tf.constant and where to use them

1. tf.constant : Value assign to the tf.constant will not be changed after 1st assignment
2. tf.variable : Valuse can be changes after assignments


In [23]:

# Defining Tensors
changeable_tensor   = tf.Variable([1,2,4])
unchangeable_tensor = tf.constant([1,2,4]) 

# Printing variables
print("Change able tensor: ",changeable_tensor,"\nUn-changeable tesnor: ", unchangeable_tensor)


Change able tensor:  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 4], dtype=int32)> 
Un-changeable tesnor:  tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [25]:
# Lets try to change the value of changeable tensor
print(changeable_tensor[0])

# So it is throwing an error emmm lets find the fix (Go to stack-overflow and see how to assign value to
# tf.variable)
changeable_tensor[0] = 2
print(changeable_tensor[0])

tf.Tensor(1, shape=(), dtype=int32)


TypeError: 'ResourceVariable' object does not support item assignment

In [32]:
# So! I found a fucntion .assign with this fucntion we can change tha value of tf.variable

changeable_tensor[0].assign(4)
print(changeable_tensor)

# Hmm! Seems that the value changed Now lets try to change the value of tf.constant

print(unchangeable_tensor[0]) 
unchangeable_tensor[0] = 4

# Emmm! Same error arrived, But we know the fix emm lets try assign function


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 2, 4], dtype=int32)>
tf.Tensor(1, shape=(), dtype=int32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [34]:
# !OOps ! Hmm now we can see that we cannot change the value of tf.constant, This is the basic difference
# between tf.constant and tf.variable
unchangeable_tensor[0].assign(4)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating Tensor of Random Array
So! Why we are practicing this, Emm! When we need to train a neural network we have to initilize weights array with some random values, which will be updated further by the neural network by forward and backward propagation (we will discuss it later), In tensorflow we use different distributions to get random variables

1. Normal Distribution, 




### Normal Distribution
In probability theory, a normal (or Gaussian or Gauss or Laplace–Gauss) distribution is a type of continuous probability distribution for a real-valued random variable. The general form of its probability density function is




#### properties of normal distributions?
Normal distributions have key characteristics that are easy to spot in graphs:

1. The mean, median and mode are exactly the same.
2. The distribution is symmetric about the mean—half the values fall below the mean and half above the mean.
3. The distribution can be described by two values: the mean and the standard deviation.

![image.png](https://cdn.scribbr.com/wp-content/uploads/2020/10/normal-distribution.png)

### Get more Insights about normal Distrubution from here

https://www.scribbr.com/statistics/normal-distribution/


## Try other distributions e.g (Uniform)

In [57]:
random = tf.random.Generator.from_seed(4)

# We are creating array of shape (3, 2) with normal distribution,
random_array = random.normal(shape = (3,2))
print(random_array)

tf.Tensor(
[[ 1.0019137   0.6735137 ]
 [ 0.06987712 -1.4077919 ]
 [ 1.0278524   0.27974114]], shape=(3, 2), dtype=float32)


# Shuffle Tensors

Why do we need to shuffle tensors. Emm! Let me explain. I am going to classify cats and dogs, and I have 10000 images,So! While reading our dataset may be first 5000 images are of cats and next 5000 images are of dogs and our model completely depends on the dataset, In first half of traning model only learn cats because first 5000 images are of cats and update its weights according to cat images and in next half model update all of its weights according to the dog images, that may slow your model training or leads you to the accuracy issues. So before feeding our data to the neural network we should always shuffle them.










In [75]:
tf.random.set_seed(42)
tf.random.shuffle(random_array)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114],
       [ 1.0019137 ,  0.6735137 ]], dtype=float32)>